# Generated by ChatGPT on 2026-01-18

from django.db import migrations, models
import media_center.models


class Migration(migrations.Migration):

    dependencies = [
        ("media_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to=media_center.models.photo_upload_to),
        ),
    ]
